# Generated by Django 4.0.4 on 2022-05-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(default=None, related_name='watched_by', to='auctions.listing'),
        ),
    ]
